name: Deploy — Prod

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PROD_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy security stack
        run: |
          az deployment sub create \
            --location swedencentral \
            --template-file infra/security/main.bicep \
            --parameters homeIpAddress='213.113.55.73' ownerEmail='sam.lekkla@outlook.com'

      - name: Deploy data stack
        run: |
          az deployment sub create \
            --location swedencentral \
            --template-file infra/data/main.bicep \
            --parameters homeIpAddress='213.113.55.73' ownerEmail='sam.lekkla@outlook.com' azureAdAdminObjectId='ebeccde8-abfd-4435-b329-f32df950d17c'

      - name: Deploy compute stack
        run: |
          az deployment sub create \
            --location swedencentral \
            --template-file infra/compute/main.bicep \
            --parameters ownerEmail='sam.lekkla@outlook.com'
